workflows:
  bucketList-workflow:
    name: BucketList
    scripts:
      - name: CICD Started
        script: echo "Hello Broski!"
      - name: Build BucketList 
        script: xcodebuild build -workspace "BucketList.xcworkspace" -scheme "BucketList" CODE_SIGN_IDENTITY="" CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO 
    publishing:
      email:
        recipients:
          - bobzhong64@gmail.com